-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 27, 2024 at 10:07 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `arba_blog`
--

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `category_id` bigint(20) UNSIGNED NOT NULL,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `image` varchar(255) DEFAULT NULL,
  `excerpt` text NOT NULL,
  `body` text NOT NULL,
  `published_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `category_id`, `user_id`, `title`, `slug`, `image`, `excerpt`, `body`, `published_at`, `created_at`, `updated_at`) VALUES
(1, 2, 3, 'Corporis voluptatem soluta et adipisci.', 'beatae-consectetur-voluptate-molestias-quae-et-aspernatur', NULL, 'Et veritatis est autem tenetur odit. Quas blanditiis pariatur omnis quia. Ullam odit aut odit error rerum occaecati aut.', '<p>Qui consequatur autem qui velit sit saepe ut. Enim ut quibusdam dolor qui aspernatur maxime exercitationem quia. Et quibusdam qui eos assumenda molestias delectus.</p><p>Doloremque optio atque corporis inventore et omnis consequuntur. Voluptatibus itaque et quo voluptas ea modi. Id quisquam qui amet possimus quos. Qui nihil sit autem et.</p><p>Sit in qui quia. Repellat sapiente dolorum praesentium sint dolorem animi. Est expedita corrupti laboriosam voluptate doloremque ut.</p><p>Eaque excepturi et iste dolorem ipsam. Quasi assumenda quaerat eaque minus perspiciatis voluptas ipsum sequi. Dolorum et similique et. At quis numquam et voluptatum facilis ratione.</p><p>Quas illum magni ea ducimus quo. Eos quis quidem libero rerum ea. Consequuntur accusamus aut culpa iure.</p><p>Laborum similique officiis voluptatem similique nam aut. Enim commodi autem enim culpa fugiat. Perspiciatis et vero et dolor doloremque. Laborum omnis quo ipsa vel aspernatur ullam.</p><p>Quasi reprehenderit cum sunt maxime. Dolor aspernatur omnis facilis in qui. Veniam officiis repudiandae et.</p><p>Qui aut deserunt ullam et ea autem vero enim. Laboriosam impedit consequatur rerum quis officia et. At deserunt voluptas ex rerum modi omnis optio. Alias necessitatibus excepturi ipsa.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(2, 1, 1, 'Ut voluptatem similique odit.', 'nihil-sequi-architecto-voluptatem-earum-sed-molestias', NULL, 'Consequatur expedita quo eligendi animi quo est sit. Sit sunt et vel ut. Sint cupiditate soluta id.', '<p>Consequatur nisi qui ipsam ratione. Omnis iste ratione voluptatem vitae. Itaque provident animi aut numquam.</p><p>Dicta iure commodi sapiente quas quia perferendis officiis modi. Numquam saepe necessitatibus voluptate maiores labore voluptate. Aut itaque maiores suscipit architecto fuga et.</p><p>Eum ea ut saepe dolorum libero delectus alias. Vitae dolores doloremque cumque recusandae laboriosam. Adipisci esse eos sint impedit maxime.</p><p>Ipsum dolor corrupti occaecati fugiat. Dignissimos aliquid incidunt suscipit ex. Dicta id deserunt consectetur voluptatem et esse.</p><p>Mollitia excepturi velit omnis fugit. Alias perspiciatis alias fugit totam excepturi quo. Aut non cum sunt. Nobis pariatur reprehenderit modi iure.</p><p>Nobis sed est corporis. Eos possimus vero laborum nemo fugiat.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(3, 2, 1, 'Sapiente eos.', 'nemo-hic-molestiae-sed-in-magni', NULL, 'Magnam est recusandae facilis laudantium sunt quod temporibus. Sequi voluptatum consequatur aut commodi. Et non autem omnis esse eaque. Vero rerum velit explicabo beatae et. Modi voluptas non voluptatem.', '<p>Nulla aut quo deserunt reiciendis voluptatibus iste autem. Dolorem sed sunt tempore deleniti tempore ducimus. Ad sunt dolore ut et et consequatur vitae.</p><p>Qui natus porro quam non nihil. Totam est et ut dolores non nobis in. Maiores et sit sit laudantium molestiae et nostrum. Laboriosam et quaerat eligendi aut illo repellat ducimus.</p><p>Explicabo perferendis ipsa enim exercitationem amet aut. Quia a nostrum ratione quae in. Odit officia unde possimus qui.</p><p>Dolorem quia nemo ut ex inventore in. Eum repudiandae pariatur sapiente et molestias sint. Magni et dolorem cum. Porro qui quia reprehenderit doloremque.</p><p>Facere ab amet sapiente laudantium asperiores quis qui. Exercitationem est iure doloremque. Corporis aut adipisci nostrum.</p><p>Velit quisquam delectus qui dolor aliquid explicabo. Aut illo sit asperiores. Blanditiis molestiae omnis ratione.</p><p>Quae beatae aliquam sequi quisquam dolores voluptatem laboriosam. Qui consectetur est sequi consectetur voluptatem eveniet. Eveniet consequatur neque possimus voluptas.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(4, 2, 1, 'Consequatur non dolore ipsam cupiditate cupiditate quae magnam magnam.', 'ad-suscipit-dignissimos-harum', NULL, 'Quas beatae fugit labore. Non temporibus rem nulla reprehenderit. Ipsam repellat aut illo quia. Tempora consectetur eius sit aut.', '<p>Sed deserunt officia illo quis. Sapiente tenetur maxime magni voluptatibus maiores. Itaque sed est et earum possimus est nisi aperiam.</p><p>Ea maiores totam ut id dolores vel animi. Voluptatibus sit pariatur praesentium rem enim. Asperiores delectus neque dolorem iste. Debitis repellat repellendus consequatur ipsam laborum.</p><p>Et illo recusandae aut ipsam exercitationem. Eligendi id enim recusandae fugit qui quisquam ut nihil.</p><p>Deleniti voluptatem vitae aliquam aperiam porro repellendus ipsa. Fuga et deleniti consequatur iste sunt. Neque et aut assumenda vero.</p><p>Suscipit ipsum eos molestiae culpa. Qui vero molestiae blanditiis impedit aut. Vero eius quasi velit laborum laboriosam distinctio.</p><p>Neque fugiat quidem et asperiores et deleniti tempora. Totam et beatae id omnis quod quis provident consequatur. Voluptatum maxime consequatur porro ut ullam.</p><p>Quo eligendi rerum similique eaque minima minus necessitatibus. Suscipit velit quasi cum veritatis quia provident. Quia ipsum provident assumenda consequatur in sint voluptas.</p><p>Architecto iste iure omnis saepe voluptas fugiat. Quod eum voluptas ea iusto et voluptates in ut. Ea quis ut adipisci omnis.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(5, 1, 1, 'Fugit velit maxime eum occaecati.', 'nesciunt-cum-sit-in-aut-voluptas', NULL, 'Aut quo quisquam dolore voluptatibus. Atque alias impedit sit ad rerum. Quia quae iste quia et enim.', '<p>Vel sed rerum dolor repellat consequatur repudiandae aliquid consectetur. Nulla cum repudiandae excepturi ut voluptate. Sit corporis provident laborum culpa. Explicabo voluptatum quo facilis aperiam doloremque ut.</p><p>Quia ea similique sit cum excepturi sunt laborum corporis. Dicta ullam nobis et reiciendis delectus tenetur. Est enim eligendi dolor. Autem tempora velit quaerat corporis.</p><p>Quod autem quia ipsam molestias iste et. Et consequatur soluta et quia distinctio non. Non autem voluptas dignissimos.</p><p>Nulla voluptatem nisi qui molestias ullam. Aut et ut qui qui deserunt accusantium quibusdam. Fuga non sed vel iste.</p><p>Inventore iste quam ut in et necessitatibus id reiciendis. Veniam tempora sed dolor voluptas hic sint aut. Eaque aperiam molestiae tenetur sed.</p><p>Error eos dolorem sapiente. Enim aut neque adipisci porro eaque aut minima. Facilis iste facere quia et ea nostrum.</p><p>Quos ab ut illo ullam qui et. Pariatur accusantium est aut vitae natus quos nam. Explicabo maxime architecto et odit et. Ratione maxime deserunt sunt ullam quis velit illum qui. Blanditiis fugit sunt autem eos ut accusantium eaque.</p><p>Similique incidunt aut fuga vitae. Beatae ullam et voluptas quibusdam quas. Pariatur in est officia. Odit veritatis eligendi odio voluptatum quam ipsum.</p><p>Molestias perferendis sed voluptatem non ullam ut. Provident expedita consequatur laborum ipsa ut. Beatae molestiae quos aut sed.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(6, 2, 1, 'Assumenda vitae quaerat ea.', 'voluptatem-eum-accusantium-qui-nihil-dolores', NULL, 'Ut molestiae ut fuga exercitationem dolorem. Et aliquid voluptatem est nam. Quam dicta maiores quo. Modi veritatis rerum illo tenetur.', '<p>Iusto et magnam accusamus quia quia saepe enim similique. Voluptas ut adipisci et sit ipsa est.</p><p>Voluptatem vitae harum officia non. Qui asperiores rerum perferendis. Est deleniti eos voluptatum voluptatem repellendus nihil dolorem. Illum aliquid excepturi est et non.</p><p>Dolor aut sed sunt rerum. Ut eum et voluptatem animi aspernatur amet. Nisi corporis deleniti earum.</p><p>In nobis dicta quae molestiae fugiat. Quae sed odit veritatis qui amet enim facilis. Et magni id praesentium eum.</p><p>Et sed omnis et quisquam tempore. Sed deserunt ipsum laboriosam qui nam. Harum eligendi distinctio ut est sed. Et officiis eius temporibus et.</p><p>Repellendus delectus est quia. Sint ut aut excepturi neque quibusdam est voluptas. Molestias soluta ut et autem dolore. Aspernatur sit atque autem laboriosam autem.</p><p>Ab possimus distinctio ducimus et molestiae nostrum nemo qui. Laborum iste voluptatem facere aut consequatur quo est laudantium.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(7, 1, 3, 'Itaque voluptatem sint.', 'et-aut-hic-blanditiis-quam-fugit', NULL, 'Dolorum ut reprehenderit et voluptate sint soluta sed. Consequuntur dolores qui dolores ipsa.', '<p>Quia maiores non quibusdam fugiat facere sapiente. Et aut itaque quia sed. Dignissimos molestias sunt error non sit.</p><p>Qui saepe non nostrum sint qui velit aut. Iure deleniti rerum quod corporis reiciendis. Perspiciatis doloribus voluptas dolores quibusdam. Et explicabo placeat ducimus quibusdam sit molestiae.</p><p>In expedita cumque commodi vitae consectetur qui est. Amet sequi officiis ratione libero. Enim vel quod tenetur omnis dolores iure non. Ut qui enim hic eum voluptatem ad nemo.</p><p>Quis error at deleniti qui enim. Deleniti repellat quia velit architecto labore. Nihil quod sit ipsa. Similique iusto eveniet natus dolor optio rem.</p><p>Ipsam aut dolore ipsam dicta aut velit esse reiciendis. Qui adipisci soluta molestiae veniam. Et blanditiis ut sint nemo tenetur omnis aut. Consectetur similique reiciendis consequatur sed nulla qui ut eveniet.</p><p>Quis odio optio et earum debitis quis. Ea maxime quia voluptas doloremque dolore perspiciatis.</p><p>Necessitatibus blanditiis nisi dignissimos quos dolor molestiae vero. Ipsam explicabo eligendi alias voluptas quia numquam pariatur. Fugiat fugit recusandae ullam aut. Aut iure mollitia fugiat magni architecto quae.</p><p>Repudiandae quaerat deserunt reiciendis et quo. Id inventore nemo aut enim est impedit esse placeat. Error sequi quia nobis quod in. Quasi et consequatur quia omnis enim ut qui. Est magni sit debitis aut.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(8, 2, 3, 'Ut dignissimos dolores.', 'ut-expedita-expedita-architecto-sapiente-tempore-reiciendis-laborum', NULL, 'Est ipsa voluptates sit impedit sed. Eaque doloribus esse laudantium reprehenderit. Ipsam porro vitae ut qui qui id optio.', '<p>Hic laboriosam modi qui et assumenda necessitatibus aperiam. Sit placeat quae quos reprehenderit et eveniet sit. Beatae qui et quam et.</p><p>Dolore quas reprehenderit nobis. Eaque ea omnis quia nulla accusamus explicabo. Exercitationem vitae sint inventore tempora qui. Aspernatur dolor quaerat aliquid omnis.</p><p>Maxime iusto error totam consequatur ut nesciunt eum. Fugiat repudiandae voluptas reiciendis rerum aut sed et. Fugiat est iste praesentium quam numquam.</p><p>Fuga eos est cumque quos aut qui. Omnis voluptatem recusandae perspiciatis. Ex velit voluptatibus placeat cumque aut voluptatem. Voluptatem doloremque ea impedit officia et cumque.</p><p>Non omnis qui non ut adipisci dolorem. Alias est ad quia a.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(9, 1, 2, 'Placeat perferendis nobis facilis veniam numquam natus blanditiis.', 'doloribus-sit-est-harum-facere-adipisci-sapiente-enim-ullam', NULL, 'Nisi ullam sit aut dolor. Officia laborum hic qui aliquam quisquam et et. Eligendi harum et vel impedit libero delectus expedita.', '<p>Quaerat nihil similique omnis sed. Consectetur praesentium suscipit doloribus deleniti et enim ipsa.</p><p>Repellat officiis quod provident praesentium distinctio non possimus. Eos sit dicta voluptas voluptatem omnis nobis qui dolorum. Dolores aperiam quam et culpa laudantium id. Sed provident provident nulla quis voluptatem ab.</p><p>Consequatur rerum numquam rerum id quis. Et voluptatibus possimus cum error perferendis amet debitis. Illum harum aperiam et qui aut officia aut. Reprehenderit omnis error inventore sunt odio.</p><p>Quam voluptatum eum dolorem consectetur aut ut dignissimos. Quo velit nobis dolores ut quo recusandae qui. Possimus ad corporis modi tempore. Ut eaque qui eum explicabo nihil iure.</p><p>Est dolore consequatur sed soluta corrupti. Reiciendis autem libero aliquid cupiditate. Aut quaerat veritatis sit rerum similique vero. Qui porro nihil fugiat voluptas aliquid est.</p><p>Eum nihil voluptas illum quis et. Est cumque sequi consequatur est a autem aspernatur. Aperiam aut voluptatem hic voluptatem ut eligendi.</p><p>Non nisi nobis et et eum delectus. Dolor officiis voluptatem necessitatibus. Nisi sit sint commodi eos eveniet.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(10, 1, 1, 'Odit consequuntur exercitationem rem maiores id.', 'sint-impedit-a-debitis-consequatur', NULL, 'Ea est repellendus velit nihil. Et omnis assumenda illo neque id sunt maxime. Exercitationem cumque mollitia impedit sapiente dolore. Quam at deserunt necessitatibus veritatis nihil.', '<p>Quidem beatae consequatur numquam sapiente. Recusandae eum porro culpa quia nihil facere culpa. Sunt temporibus vitae hic et magni eaque et nisi. Officia eos harum ipsum itaque provident velit quae.</p><p>Et asperiores repellendus vel dolor modi. Dignissimos magnam est expedita iure aut ad. Repudiandae officiis error est reiciendis nam fugit. Suscipit est consequatur dolore vitae voluptas.</p><p>Iste quod reprehenderit quisquam ipsum alias voluptate cumque. Rerum qui suscipit ipsum consectetur magni qui nobis sed. Quo modi libero et recusandae dolores consequuntur fugiat. Assumenda sed aut voluptatum expedita dolor laboriosam qui.</p><p>Odio et excepturi tempore dolorum quasi nesciunt. Voluptates eius assumenda atque atque voluptatem quia. Odit totam ullam voluptas quo temporibus ab. In soluta iste est magnam. Qui aliquam in id magni.</p><p>Fuga vitae exercitationem amet et rerum quo. Commodi reprehenderit in iusto aliquam. Atque eaque aspernatur inventore praesentium quod et.</p><p>Ut dolorem nisi sunt ex dicta sed perferendis. Quaerat nisi quia velit et. Culpa qui et ab explicabo sapiente repudiandae atque.</p><p>Quam voluptas tempora ut sunt sed sunt. Commodi et omnis odio. Qui enim omnis minus consequatur nisi quis.</p><p>Qui assumenda porro quas enim non. Saepe nihil est quam sed quisquam labore amet. Magnam qui perferendis ea sapiente asperiores incidunt itaque aut.</p><p>Nisi neque laborum dolorum nam repellat placeat placeat. Sequi dicta sunt autem eius cupiditate corrupti. Ut molestias assumenda debitis ratione.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(11, 1, 1, 'Eos ea eos aspernatur excepturi.', 'iure-inventore-dignissimos-non-ad-quo-voluptate-quia-impedit', NULL, 'Tenetur suscipit veniam repellendus. Consequatur aperiam numquam illum cumque dolorum sit. Sunt quia quae veritatis occaecati distinctio id. Consectetur perspiciatis ad ea quod ut.', '<p>Aperiam rerum ut voluptatem sint. Quia occaecati cupiditate velit odit id. In temporibus ut exercitationem.</p><p>Exercitationem voluptatum pariatur tempora necessitatibus adipisci. Et deserunt maiores repellendus modi praesentium. Necessitatibus tenetur occaecati aut blanditiis voluptate illo. Aut eos est quas et qui sunt. Consectetur est corrupti aliquid rem cupiditate commodi.</p><p>Sed earum debitis non fugit dolore aut. Omnis tempora aliquam similique aspernatur et repellat ullam ratione.</p><p>Sed saepe nihil similique earum. Fuga dolorum eum facilis ea quo. Nesciunt aut iusto recusandae commodi.</p><p>Et deserunt et qui consequatur tenetur in consectetur rerum. Dolorum quia explicabo dolorem quis rerum eveniet. Iure aspernatur qui molestias perferendis ducimus.</p><p>Debitis ab ex ea nostrum explicabo. Suscipit rerum perferendis ut maxime ab. Expedita sequi nulla occaecati sit omnis aperiam quas.</p><p>Minima est ipsa itaque cupiditate tempore est porro. Perferendis voluptate officia veniam vero. Illo sit est voluptatem veritatis aperiam.</p><p>Voluptas soluta neque ab at qui. Optio animi veniam officia quia. Alias modi ducimus tempore minima non ut vero.</p><p>Magnam aut sit veniam et quisquam in autem. Placeat eius ex ea quaerat perspiciatis. Quas quibusdam in cumque et voluptate.</p><p>Optio quia itaque eligendi iste. Et molestiae assumenda debitis. Modi ipsa eos ut sunt.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(12, 1, 1, 'Perspiciatis ut neque quasi neque voluptatem accusantium.', 'repellat-vero-deleniti-architecto', NULL, 'Quae est fugiat sit aut dolores rem ipsa sed. Et culpa laboriosam tempora sequi nesciunt. Et tempora natus nam molestiae. Sequi et saepe dolorem ut repudiandae quia ut.', '<p>Neque maxime non autem non perferendis. Odit eveniet omnis necessitatibus molestiae. Ab pariatur quisquam ab voluptatum inventore eveniet.</p><p>Neque voluptas officiis eos expedita sint ut. Debitis delectus odio dignissimos est quibusdam omnis aut. Quo eos mollitia fugit quae neque amet. Temporibus quidem in soluta.</p><p>Beatae non quaerat itaque. Commodi aliquam ipsa delectus vel voluptatem. Rem rerum dignissimos impedit necessitatibus numquam commodi et voluptates.</p><p>Dolorem vero numquam quo vel maxime. Molestiae officiis autem et aspernatur. Aut sit beatae natus temporibus fuga dicta ea.</p><p>Doloremque dolorem deserunt saepe aspernatur perspiciatis ut. Voluptates quae molestiae optio omnis ut optio. Possimus harum labore est sed architecto. Beatae laboriosam incidunt voluptatem assumenda.</p><p>Veritatis sed nulla alias perspiciatis possimus incidunt fugiat nostrum. Rem qui nam voluptatem. Veritatis omnis vitae aspernatur quia aut consequatur. Consequatur omnis sapiente expedita quos ut dicta.</p><p>Mollitia odit sit placeat velit est nihil molestiae. Fugit numquam accusantium voluptatibus nulla repudiandae sint.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(13, 2, 3, 'Inventore voluptas quia.', 'non-voluptatem-pariatur-laboriosam-id-eos-eos-tempore', NULL, 'Ut modi dolor odit repellat culpa. Ea exercitationem sit ratione. Quia natus pariatur quisquam architecto odio. Dolorem omnis illo sint beatae sed dolor.', '<p>Quae eius commodi sunt rerum impedit laudantium. Dignissimos id esse praesentium ab consectetur. Suscipit rerum vero natus rerum est similique officia.</p><p>Dicta earum suscipit qui hic omnis. Et nostrum dolor mollitia quas dolores error consequatur. Quibusdam ex sunt consequatur laborum rerum minus. Dolor beatae et nihil molestiae corrupti et libero optio.</p><p>Amet nam aut est eos. Animi blanditiis quisquam dolor quos sed rem. Ut minus et atque quia temporibus provident nobis repudiandae.</p><p>Asperiores qui accusantium quia dolorum illum. Incidunt aut sint perspiciatis numquam quisquam aut. Ratione debitis doloribus eum eligendi ut perferendis possimus inventore. Et ratione aut est quas.</p><p>Eos voluptas dolor impedit eos. Et est id facere nobis explicabo.</p><p>Molestiae praesentium tenetur velit et impedit qui molestias. Et cupiditate et quam reiciendis molestiae autem consequuntur eum.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(14, 2, 1, 'Harum nesciunt ipsa ut.', 'et-provident-eum-et-molestias', NULL, 'Nemo rem corrupti doloremque praesentium perferendis culpa consequatur quasi. Deserunt qui laborum dolorem voluptatem. Qui corrupti et voluptatem autem quis quasi. Sit veritatis placeat qui blanditiis quas.', '<p>Dolore repellat quod ut pariatur. Nihil tempora molestiae enim ex eligendi sunt. Molestias odit neque maiores qui.</p><p>Quos occaecati perspiciatis porro laudantium odit. Accusantium minus laboriosam sed eum numquam reiciendis perspiciatis. Nihil occaecati excepturi occaecati magni nisi adipisci neque. Autem reiciendis molestias facilis quia aperiam.</p><p>Corporis necessitatibus nobis animi sint repudiandae tempora. Cupiditate id reprehenderit voluptates unde placeat eveniet eveniet. Perspiciatis accusamus a error voluptas. Rerum aut non quam facere vero.</p><p>Quam nam et quia aliquam. Vero deserunt similique deserunt quasi sequi. Saepe consequatur qui reiciendis molestias in ut.</p><p>Voluptatem maiores labore voluptatem beatae. At illum blanditiis quia in aut.</p><p>Deserunt fuga quae dolores similique voluptatem est ipsum. Ullam eos aliquid eos sit ut expedita. Omnis ratione consequuntur dolorem rerum enim.</p><p>Eum ipsa sed velit perferendis ut. Corporis maiores ullam odio veniam voluptatem veritatis. Illum aut nobis quia est et numquam.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(15, 2, 1, 'Id labore in.', 'suscipit-voluptas-placeat-natus-explicabo-vel-sed-sed', NULL, 'Non facilis quis possimus sunt reprehenderit. Ut consequuntur autem eum culpa. Et qui non cumque quae sint harum deserunt. Dolore tenetur eligendi laboriosam esse numquam laudantium dolores.', '<p>Cumque exercitationem repellendus est. Illo excepturi magni aliquid modi possimus atque sit voluptates. Temporibus et et nihil et illum.</p><p>Quia commodi doloribus qui quia numquam assumenda quidem. Esse ad sunt aut ut illo. Fugiat ut qui et dicta saepe. Doloribus ut placeat sint est qui expedita.</p><p>Nobis alias aspernatur suscipit alias. Dolores velit dignissimos placeat reprehenderit sapiente consectetur. Dolore velit cumque est. Repudiandae nisi quis voluptate odio.</p><p>Quo vitae est aut enim aliquam magnam. In id est aut quas neque totam esse illo. Eum amet expedita inventore provident.</p><p>Est deleniti asperiores mollitia beatae. Dolorem possimus ut aliquid possimus iste.</p><p>Saepe vero vitae iusto dolorem dolorum. Tempore officia asperiores voluptatum labore praesentium dolorem. Similique quas distinctio maxime eum.</p><p>Sint tenetur laborum quod ut ipsum. Id sed cupiditate sint enim repellendus commodi. Dolorum et ut asperiores nisi voluptatem.</p><p>Blanditiis ullam fuga quo. Laboriosam molestiae aliquid qui. Omnis id rem aut. Numquam sequi occaecati sapiente quo voluptatum. Sed reprehenderit repudiandae enim voluptatem.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(16, 1, 3, 'Quae iste quaerat eos vel.', 'quibusdam-aliquam-nesciunt-sed-qui-at', NULL, 'Odit voluptate doloribus eum nemo ipsa dolore. Ut aut ipsa quis. Atque nam consequatur dolorum id a nihil rerum. Aspernatur velit sit illo quaerat exercitationem sed quidem.', '<p>Cumque magni vero aut et voluptas fugit cupiditate. Dicta possimus dicta sed ex et sed est. In et repudiandae et sequi quibusdam rerum.</p><p>Maiores sed est pariatur qui vel odit. Nobis quia voluptatem at non non. Deserunt voluptate nihil rerum ut. Omnis magnam odio fugit dolorem repellendus.</p><p>Et qui dolorem vel aut vitae consequatur. Dolore cum ullam numquam sapiente nulla et et. Voluptas magnam sunt sit. Aspernatur quod sequi qui omnis excepturi.</p><p>Quis omnis quis consequatur et corrupti sit quis. Reiciendis aspernatur culpa et eligendi eveniet ipsum tenetur officiis. Quo expedita corporis quia aut adipisci consequatur commodi.</p><p>Consequatur dolor inventore delectus quibusdam repellat a omnis. Qui voluptas nisi blanditiis illum et nobis sapiente nisi. Ducimus et officiis voluptatem.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(17, 1, 3, 'Iusto possimus ullam neque unde itaque.', 'suscipit-laudantium-ex-fuga-et', NULL, 'Sint molestiae placeat facilis accusantium et. Explicabo rerum et eos blanditiis quam. Quia laudantium impedit et magni et est quis. Voluptate aliquam qui labore porro consequatur perferendis.', '<p>Dolorem quibusdam ut rem dolor. Nesciunt ut eius molestiae voluptate minima. Voluptatem saepe sit pariatur animi.</p><p>Esse omnis veniam iste incidunt quo sit porro. Nesciunt consequatur deleniti earum minus dolorem maxime in. Quod aut ea mollitia quaerat modi. Repudiandae aliquam inventore tenetur ducimus beatae.</p><p>Tenetur accusantium numquam earum porro repellendus. Iste tempora mollitia et vel veniam voluptatem. Officia non sed quae itaque et sint.</p><p>Accusamus in non et neque. Ut deleniti cum velit incidunt ex.</p><p>Amet sit hic voluptatum ut. Quasi harum dolorum non temporibus repudiandae itaque quam. Repellat sunt vitae totam nihil illum maxime. Sint praesentium id aut veniam ratione adipisci perferendis.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(18, 1, 1, 'Itaque est.', 'necessitatibus-et-asperiores-id-voluptates-cumque-error', NULL, 'Dolorem similique aspernatur autem et non dolorem laudantium. Dolorem iste qui autem et. Quo iste error est sit laborum accusantium sit.', '<p>Recusandae sed unde qui quis illum eaque. Non eum vel provident quia numquam vero. Ad doloremque illo aperiam omnis fugit eos odio. Non odit quas minus sit modi.</p><p>Sunt cum aspernatur ipsum quisquam. Consequuntur et quia laudantium reprehenderit. Quis nulla nam voluptas voluptas.</p><p>Quis qui in corrupti velit quidem impedit odit. Dolores voluptas voluptas dolor iure debitis sint ullam. Velit necessitatibus laborum facere voluptatum ut possimus doloremque. Molestiae deserunt incidunt nisi minus excepturi.</p><p>Sed molestias a et rem velit. Similique iure error quis ea. Ut itaque amet magni blanditiis qui corporis.</p><p>Reprehenderit sed impedit blanditiis hic mollitia. Quia velit molestiae adipisci ullam possimus pariatur facere. Sit et quo ullam incidunt reiciendis repellat incidunt. Cupiditate illo tempore omnis omnis sint velit.</p><p>Voluptatibus et nihil aut reprehenderit eveniet dolorem error. Molestiae quam consequatur qui delectus doloribus. Quo expedita a quia culpa.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(19, 1, 1, 'Quaerat quos.', 'consequatur-ipsum-sint-vero-est-aut-dolor-nostrum-cum', NULL, 'Autem tenetur distinctio odit et dolor. Omnis accusamus ipsam in ab dolorem. Minima ut dolor illum dolore asperiores ex ullam dolores.', '<p>Et unde quia voluptas pariatur qui pariatur ut. Illum autem aut repellendus sapiente molestiae ea nesciunt nihil. Ipsum enim praesentium culpa id aperiam sit et.</p><p>Voluptate odit est placeat rerum est. Dolorem ea minima voluptates illo cum. Ut eveniet deserunt culpa rerum quo in unde. Expedita voluptatem repellat architecto tempore.</p><p>Consequuntur soluta ratione quaerat cumque ducimus. Ullam animi nihil nostrum inventore. Quos error et consequatur.</p><p>Aut sed omnis qui in impedit. Ea quas hic saepe. Et laboriosam beatae ut aut doloremque.</p><p>Minus ea et possimus quia labore eveniet. Numquam natus consequatur non numquam ullam consectetur assumenda. Sunt recusandae sed et quo aut aut tempore.</p><p>Aut molestiae quia sit sit omnis. Omnis quia magni a dolorem et pariatur. Sed autem perferendis natus.</p><p>Nulla reiciendis sint et aperiam porro corrupti. Vel eos quo vel eos cum veritatis quisquam. Cumque quam nemo impedit necessitatibus ex voluptatibus qui.</p><p>Voluptatem quam maiores nemo consequatur voluptas ullam. Quaerat nesciunt harum temporibus at rem. Velit commodi autem error et.</p><p>Ut alias et aliquam in aliquam modi omnis accusamus. Voluptas non debitis et nesciunt ea. Voluptatem et itaque sint aut vel architecto eum.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(20, 2, 1, 'Eos aspernatur.', 'fugiat-nisi-delectus-praesentium-ipsam-voluptate-tempora-placeat', NULL, 'Voluptatem et quis aut officia est. Rerum itaque suscipit est. Voluptatem deserunt est sint adipisci qui laboriosam porro. Dolores libero suscipit qui ullam. Debitis non voluptatum sed architecto nobis eaque.', '<p>Dolor eos dolor assumenda porro omnis molestiae tempore. Excepturi voluptas est ut ipsum consequatur velit ut libero. Praesentium iure rerum et minus.</p><p>Sit doloribus dolore corrupti architecto. Velit non earum saepe tenetur. Dolore impedit nulla doloribus ut.</p><p>Pariatur et nihil expedita inventore quas dolore. Harum quo quia nobis officia. Id ipsum necessitatibus consequuntur eos dolorem sed aut.</p><p>Sapiente rerum rerum corrupti nisi. Et autem itaque fugit expedita natus eum ullam accusamus. Et perspiciatis enim est deleniti mollitia maxime perferendis. Quo et eaque est. Neque cupiditate et officia.</p><p>Et est facilis repellendus ducimus magnam nesciunt eius. Commodi iste corrupti quibusdam perferendis recusandae est. Et eum ab modi tenetur.</p>', NULL, '2024-04-10 06:35:07', '2024-04-10 06:35:07'),
(21, 3, 1, 'Black Asta Power\'s', 'black-asta-blog', 'post-images/6ESsYAEkE8ngf4NP5og5Esg7VxIVDuvqd1xUcUh9.jpg', 'Black Asta Power\'s', '<div><strong>Black Asta Power\'s</strong></div>', NULL, '2024-04-10 07:54:11', '2024-04-10 07:54:11');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `posts_slug_unique` (`slug`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=23;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
